[docker]

# GeoAPI settings
BASE_URL = "http://geoapi:5000/"
LISTEN_TO = "0.0.0.0"
PORT = 5000
DEBUG = true

# Data settings
CLIENT_TIMEZONE = "America/Argentina/Buenos_Aires"
COORDINATE_SYSTEM = "EPSG:4326"
DEFAULT_CHUNKSIZE = 50

# Geoserver settings
GEOSERVER_BASE_URL = "http://geoserver:8080/"
GEOSERVER_USERNAME = "admin"
GEOSERVER_PASSWORD = "geoserver"
GEOSERVER_WORKSPACE = "geoapi"
GEOSERVER_DATASTORE = "postgis"
GEOSERVER_STYLE_STORAGE = "/opt/geoserver_data/styles"

# PostGIS settings
POSTGIS_HOST = "postgis:5432"
POSTGIS_USER = "geoserver"
POSTGIS_PASS = "geoserver"
POSTGIS_DATABASE = "geoserver"
POSTGIS_SCHEMA = "geoapi"
POSTGIS_DRIVER = "postgresql+psycopg2"
POSTGIS_TIMEZONE = "UTC"

# CELERY Settings
CELERY_BROKER = "redis://redis:6379/0"
TEMP_BASE = "/tmp"
