CREATE SCHEMA IF NOT EXISTS geoapi;

DROP EXTENSION IF EXISTS postgis CASCADE ;
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA geoapi ;
CREATE EXTENSION IF NOT EXISTS postgis_raster WITH SCHEMA geoapi ;
CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA geoapi ;

-- DROP SCHEMA IF EXISTS public CASCADE ;

GRANT USAGE, CREATE ON SCHEMA geoapi TO geoserver;

GRANT ALL ON ALL TABLES IN SCHEMA geoapi TO geoserver;
